#.bash_profile

if [ -x "$HOME/.profile" ]; then
	source "$HOME/.profile"
fi

set -o vi

if [ -x "/Applications/Racket/share/pkgs/shell-completion/racket-completion.bash" ]; then
	source "/Applications/Racket/share/pkgs/shell-completion/racket-completion.bash"
fi

if [ -e "${HOME}/.iterm2_shell_integration.bash" ]; then
	source "${HOME}/.iterm2_shell_integration.bash"
fi

if [[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]]; then
	source "/usr/local/etc/profile.d/bash_completion.sh"
fi

export PAGER="most"
