# .zsh_profile

if [ -x "$HOME/.profile" ]; then
	source "$HOME/.profile"
fi

fpath=(/usr/local/share/zsh-completions $fpath)

if [ -x "$HOME/.iterm2_shell_integration.zsh" ]; then
	source "$HOME/.iterm2_shell_integration.zsh"
fi

if [ -x "/Applications/Racket/share/pkgs/shell-completion/racket-completion.zsh" ]; then
	source "/Applications/Racket/share/pkgs/shell-completion/racket-completion.zsh" 
fi

bindkey -v

setopt AUTO_CD
setopt BASH_AUTO_LIST
setopt COMPLETE_IN_WORD
setopt LIST_PACKED
setopt ZLE
