# .zshrc

if [ -x "$HOME/.zsh_profile" ]; then
	source "$HOME/.zsh_profile"
fi

if [ -x "$HOME/.iterm2_shell_integration.zsh" ]; then
	source "$HOME/.iterm2_shell_integration.zsh"
	PS1=%{$(iterm2_prompt_mark)%}$PS1
fi

export EDITOR='vim'

export PAGER='most'

setopt EXTENDED_GLOB
if [ -e "$HOME/.zprezto/init.zsh" ]; then
	source "$HOME/.zprezto/init.zsh"
fi

