# .zshrc

if [ -x "$HOME/.zprofile" ]; then
	source "$HOME/.zprofile"
fi

if [ -x "$HOME/.iterm2_shell_integration.zsh" ]; then
	source "$HOME/.iterm2_shell_integration.zsh"
	PS1=%{$(iterm2_prompt_mark)%}$PS1
fi

export EDITOR='vim'

export PAGER='most'

if [ -e "$HOME/.zprezto/init.zsh" ]; then
	source "$HOME/.zprezto/init.zsh"

	autoload -Uz promptinit
	promptinit
	prompt agnoster
fi

